"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "motion/react";
import { AppWindow, ArrowRight, Bell, Building2, Check, ChevronDown, CircleHelp, Clock3, FileText, FolderKanban, Grid2X2, Home, LogOut, Menu, MessageCircleMore, Palette, PenLine, Search, Settings, ShieldCheck, ShoppingBag, Sparkles, Upload, UserRound, UsersRound, X } from "lucide-react";
import type { User } from "@/lib/types";
import { useGOSStore } from "@/lib/store";
import { Logo } from "./logo";

const appData = [
  {id:"project",name:"Project Admin",description:"Projects and delivery",Icon:FolderKanban,tone:"orange"},
  {id:"documents",name:"DocuWeave",description:"Documents and work",Icon:FileText,tone:"purple"},
  {id:"signflow",name:"Signflow",description:"Digital signatures",Icon:PenLine,tone:"blue"},
  {id:"vendors",name:"Vendor Management",description:"Vendors and compliance",Icon:UsersRound,tone:"green"},
  {id:"echo",name:"Echo",description:"AI collaboration",Icon:MessageCircleMore,tone:"slate"},
];
const wallpapers=[{id:"aurora",name:"Midnight aurora"},{id:"mountain",name:"Cape sunset"},{id:"graphite",name:"Graphite"}];
const nav=[{label:"Home",Icon:Home},{label:"Search",Icon:Search},{label:"Apps",Icon:Grid2X2},{label:"People",Icon:UsersRound},{label:"Vendors",Icon:Building2},{label:"Marketplace",Icon:ShoppingBag}];

export function Workspace({user}:{user:User}){
  const router=useRouter(), {tenantId,setTenantId,wallpaper,setWallpaper}=useGOSStore();
  const [tenantOpen,setTenantOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[mobileNav,setMobileNav]=useState(false),[query,setQuery]=useState(""),[now,setNow]=useState<Date|null>(null),[toast,setToast]=useState("");
  const tenant=user.tenants.find(t=>t.id===tenantId)??user.tenants[0];
  const apps=useMemo(()=>appData.filter(a=>tenant.apps.includes(a.id)&&(`${a.name} ${a.description}`.toLowerCase().includes(query.toLowerCase()))),[tenant,query]);
  useEffect(()=>{setNow(new Date());const i=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(i)},[]);
  function launch(name:string){setToast(`${name} is ready to launch`);setTimeout(()=>setToast(""),2400)}
  async function logout(){await fetch("/api/logout",{method:"POST"});router.push("/login");router.refresh()}
  return <main className={`desktop wallpaper-${wallpaper}`}>
    <button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}><Menu/></button>
    <aside className={`sidebar ${mobileNav?"open":""}`}><Logo/><nav>{nav.map(({label,Icon},i)=><button key={label} className={i===0?"active":""} onClick={()=>{setMobileNav(false);if(label!=="Home")launch(label)}}><Icon/>{label}</button>)}</nav><div className="side-secondary"><button><Bell/>Notifications <b>3</b></button><button><CircleHelp/>Help</button><button onClick={()=>setSettingsOpen(true)}><Settings/>Settings</button></div><button className="profile" onClick={()=>setSettingsOpen(true)}><span>AR</span><div><strong>{user.name}</strong><small>{tenant.role}</small><small>{tenant.name}</small></div><ArrowRight/></button></aside>
    <section className="desktop-main"><header className="topbar"><div className="global-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything in GOS…"/><kbd>⌘ K</kbd></div><div className="top-actions"><button aria-label="AI assistant"><Sparkles/></button><button><Grid2X2/></button><button className="bell"><Bell/><i>3</i></button><button className="tenant-button" onClick={()=>setTenantOpen(!tenantOpen)}>{tenant.name}<ChevronDown/></button><button className="avatar">AR<span/></button></div>{tenantOpen&&<div className="tenant-menu"><p>Switch organisation</p>{user.tenants.map(t=><button key={t.id} onClick={()=>{setTenantId(t.id);setTenantOpen(false)}}><span>{t.shortName.slice(0,2).toUpperCase()}</span><div><strong>{t.name}</strong><small>{t.role} · {t.deployment}</small></div>{t.id===tenant.id&&<Check/>}</button>)}<hr/><button onClick={logout}><LogOut/>Sign out</button></div>}</header>
      <div className="content"><div className="hero"><div><span className="eyebrow">GOOD {now&&now.getHours()<12?"MORNING":now&&now.getHours()<18?"AFTERNOON":"EVENING"}</span><h1>{user.name.split(" ")[0]},<br/>welcome to <em>GOS</em></h1><p>ONE PLATFORM. EVERY POSSIBILITY.</p></div><div className="weather"><Clock3/><div><b>{now?.toLocaleTimeString("en-ZA",{hour:"2-digit",minute:"2-digit"})??"--:--"}</b><span>{now?.toLocaleDateString("en-ZA",{weekday:"short",day:"2-digit",month:"short",year:"numeric"})}</span><span>{tenant.location}</span></div><div className="sun">☀️</div><div><b>18°C</b><span>Clear skies</span></div></div></div>
      <div className="section-head"><h2>Your workspace</h2><button onClick={()=>launch("App library")}>Open app library <ArrowRight/></button></div><div className="app-grid">{apps.map((a,i)=><motion.button initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.06}} key={a.id} className={`app-card ${a.tone}`} onClick={()=>launch(a.name)}><span className="app-icon"><a.Icon/></span><strong>{a.name}</strong><small>{a.description}</small><i><ArrowRight/></i></motion.button>)}<button className="app-card marketplace" onClick={()=>launch("Marketplace")}><span className="plus">+</span><strong>Marketplace</strong><small>Discover more apps</small></button></div>
      <div className="dashboard-grid"><Panel title="Recent activity" action="View all"><Activity icon={<FileText/>} title="RFQ-2026-0441" meta="Project Admin · 5 minutes ago" status="Updated"/><Activity icon={<FileText/>} title="Board Pack Q3" meta="DocuWeave · 18 minutes ago" status="Shared"/><Activity icon={<PenLine/>} title="Supplier Agreement" meta="Signflow · 1 hour ago" status="Completed"/><Activity icon={<UsersRound/>} title="Vendor onboarding" meta="Vendor Management · 2 hours ago" status="In progress"/></Panel><Panel title="Your notifications" action="View all"><Activity icon={<UserRound/>} title="Vendor requires approval" meta="Kalahari Systems (Pty) Ltd" status="2h ago"/><Activity icon={<Bell/>} title="Usage limit at 80%" meta="DocuWeave storage" status="5h ago"/><Activity icon={<Sparkles/>} title="New feature available" meta="Echo 2.0 is now available" status="1d ago"/></Panel><Panel title="Tenant overview" action="View details"><div className="metric wide"><UsersRound/><span>Active users<strong>{tenant.id==="gic"?128:tenant.id==="kalahari"?64:22}</strong></span><em>↑ 12%</em></div><div className="metric"><Grid2X2/><span>Applications<strong>{tenant.apps.length}</strong></span></div><div className="metric"><Building2/><span>Vendors<strong>{tenant.id==="gic"?37:12}</strong></span></div><div className="compliance"><ShieldCheck/><span>Compliance status<strong>Compliant</strong></span></div></Panel></div></div>
    </section><Dock onSettings={()=>setSettingsOpen(true)} onLaunch={launch}/>
    <AnimatePresence>{settingsOpen&&<SettingsWindow wallpaper={wallpaper} setWallpaper={setWallpaper} close={()=>setSettingsOpen(false)}/>}</AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="toast"><Check/> {toast}</motion.div>}
  </main>
}
function Panel({title,action,children}:{title:string;action:string;children:React.ReactNode}){return <section className="panel"><header><h3>{title}</h3><button>{action} <ArrowRight/></button></header>{children}</section>}
function Activity({icon,title,meta,status}:{icon:React.ReactNode;title:string;meta:string;status:string}){return <div className="activity"><span>{icon}</span><div><strong>{title}</strong><small>{meta}</small></div><em>{status}</em></div>}
function Dock({onSettings,onLaunch}:{onSettings:()=>void;onLaunch:(s:string)=>void}){return <div className="dock">{[{n:"Home",I:Home},{n:"Apps",I:Grid2X2},{n:"People",I:UsersRound},{n:"Marketplace",I:ShoppingBag},{n:"Search",I:Search},{n:"Settings",I:Settings}].map(({n,I},i)=><button className={i===0?"active":""} key={n} onClick={()=>n==="Settings"?onSettings():onLaunch(n)}><I/><span>{n}</span></button>)}</div>}
function SettingsWindow({wallpaper,setWallpaper,close}:{wallpaper:string;setWallpaper:(s:string)=>void;close:()=>void}){const[fileName,setFileName]=useState("");return <motion.div className="window-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section className="settings-window" initial={{scale:.94,y:20}} animate={{scale:1,y:0}} exit={{scale:.94,y:20}}><header><div><span/><span/><span/></div><h2>Personalise GOS</h2><button onClick={close}><X/></button></header><div className="settings-body"><aside><button className="active"><Palette/>Wallpaper</button><button><AppWindow/>Appearance</button><button><Bell/>Notifications</button><button><ShieldCheck/>Privacy & security</button></aside><div className="wallpaper-settings"><span className="eyebrow">DESKTOP</span><h3>Choose your background</h3><p>Your preference is saved to this device and follows you between tenant workspaces.</p><div className="wallpaper-grid">{wallpapers.map(w=><button key={w.id} onClick={()=>setWallpaper(w.id)} className={`wallpaper-option ${w.id} ${wallpaper===w.id?"selected":""}`}><span>{wallpaper===w.id&&<Check/>}</span><strong>{w.name}</strong></button>)}</div><label className="upload"><Upload/><span><strong>{fileName||"Upload your own image"}</strong><small>JPG or PNG · up to 10 MB</small></span><input type="file" accept="image/png,image/jpeg" onChange={e=>setFileName(e.target.files?.[0]?.name||"")}/></label></div></div></motion.section></motion.div>}
